### ISSUE TITLE
Error on line 85:96

### ISSUE THREAD

**Issue by alextu870719** [bwees/AggieSpiritWidget#1]
Error on line 85:96: TypeError: undefined is not an object (evaluating'aKey.response.cookies.filter(coolie=>cookie.name == "access_token") [0].value')

**Comment by bwees** [comment]
TAMU changed its backend once again. I am working quickly to resolve this. I am having multiple issues with the new system so it may take longer. Sorry for the inconvenience!

**Comment by alextu870719** [comment]
Thank you very much!

**Comment by bwees** [comment]
Just wrapped up the changes! Here is how to get back up and running:

1. Copy down your config from the widget. (Long press on widget > Edit widget > copy the config string)
  a. ‼️ Copy into a note, you will replace your clipboard when you copy the widget code
2. Delete the script inside of Scriptable and reinstall using the same instructions on the README. 
3. Set up the widget again and use the same config from the note from step 1. You should not need any changes.

Let me know if you have any other issues!

**Comment by alextu870719** [comment]
Fixed!
Thank you very much!

**Comment by bwees** [comment]
Just FYI I changed some code around so it will auto-update when I make changes. Please update the code from the new instructions!

**Comment by alextu870719** [comment]
OK, thank you for your maintaining.
